In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
fighter_df = pd.read_csv('raw_fighter_details.csv')
fight_df = pd.read_csv('raw_total_fight_data.csv',sep=';')

In [3]:
fighter_df.head()

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,"Jul 13, 1978",0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Papy Abedi,"5' 11""",185 lbs.,NaN,Southpaw,"Jun 30, 1978",2.80,55%,3.15,48%,3.47,57%,50%,1.3
2,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",2.45,44%,2.45,58%,1.23,24%,47%,0.2
3,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,"Jul 03, 1983",3.29,38%,4.41,57%,0.00,0%,77%,0.0
4,Hiroyuki Abe,"5' 6""",145 lbs.,NaN,Orthodox,NaN,1.71,36%,3.11,63%,0.00,0%,33%,0.0

In [4]:
fight_df.head()

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,R_TD,B_TD,R_TD_pct,B_TD_pct,R_SUB_ATT,B_SUB_ATT,R_REV,B_REV,R_CTRL,B_CTRL,R_HEAD,B_HEAD,R_BODY,B_BODY,R_LEG,B_LEG,R_DISTANCE,B_DISTANCE,R_CLINCH,B_CLINCH,R_GROUND,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
0,Adrian Yanez,Gustavo Lopez,2,0,41 of 103,23 of 51,39%,45%,41 of 103,23 of 51,0 of 0,0 of 1,---,0%,0,0,0,0,0:03,0:00,32 of 83,14 of 40,8 of 19,5 of 7,1 of 1,4 of 4,41 of 102,23 of 51,0 of 0,0 of 0,0 of 1,0 of 0,KO/TKO,3,0:27,3 Rnd (5-5-5),Chris Tognoni,"March 20, 2021","Las Vegas, Nevada, USA",Bantamweight Bout,Adrian Yanez
1,Trevin Giles,Roman Dolidze,0,0,27 of 57,32 of 67,47%,47%,43 of 73,75 of 110,1 of 2,1 of 3,50%,33%,1,2,0,1,1:15,4:15,22 of 51,10 of 37,4 of 4,7 of 14,1 of 2,15 of 16,15 of 42,28 of 59,4 of 5,3 of 6,8 of 10,1 of 2,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Herb Dean,"March 20, 2021","Las Vegas, Nevada, USA",Middleweight Bout,Trevin Giles
2,Tai Tuivasa,Harry Hunsucker,1,0,14 of 18,2 of 6,77%,33%,14 of 18,2 of 6,0 of 0,0 of 0,---,---,0,0,0,0,0:10,0:00,10 of 14,1 of 5,0 of 0,0 of 0,4 of 4,1 of 1,9 of 10,2 of 6,0 of 0,0 of 0,5 of 8,0 of 0,KO/TKO,1,0:49,3 Rnd (5-5-5),Herb Dean,"March 20, 2021","Las Vegas, Nevada, USA",Heavyweight Bout,Tai Tuivasa
3,Cheyanne Buys,Montserrat Conejo,0,0,31 of 65,15 of 41,47%,36%,49 of 87,136 of 168,0 of 0,4 of 5,---,80%,0,2,3,1,1:04,9:53,26 of 60,10 of 35,5 of 5,0 of 1,0 of 0,5 of 5,26 of 56,15 of 41,2 of 2,0 of 0,3 of 7,0 of 0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Mark Smith,"March 20, 2021","Las Vegas, Nevada, USA",Women's Strawweight Bout,Montserrat Conejo
4,Marion Reneau,Macy Chiasson,0,0,30 of 63,51 of 138,47%,36%,59 of 93,92 of 184,2 of 4,1 of 1,50%,100%,0,0,0,1,2:15,3:48,14 of 40,29 of 110,7 of 13,15 of 20,9 of 10,7 of 8,25 of 54,36 of 119,5 of 9,13 of 15,0 of 0,2 of 4,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Mark Smith,"March 20, 2021","Las Vegas, Nevada, USA",Women's Bantamweight Bout,Macy Chiasson

In [5]:
fight_df = fight_df[['R_fighter','B_fighter','Winner']]

In [6]:
df = fight_df.merge(fighter_df, how='left', left_on='R_fighter', right_on='fighter_name')
df = df.merge(fighter_df, how='left', left_on='B_fighter', right_on='fighter_name',suffixes=('_Red', '_Blue'))

In [7]:
df.head()

,R_fighter,B_fighter,Winner,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,DOB_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,fighter_name_Blue,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,DOB_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue
0,Adrian Yanez,Gustavo Lopez,Adrian Yanez,Adrian Yanez,"5' 7""",135 lbs.,"70""",Orthodox,"Nov 29, 1993",4.69,44%,2.31,55%,0.00,0%,100%,0.0,Gustavo Lopez,"5' 5""",135 lbs.,"67""",Orthodox,"Jun 27, 1989",2.24,41%,4.65,51%,1.07,50%,27%,0.5
1,Trevin Giles,Roman Dolidze,Trevin Giles,Trevin Giles,"6' 0""",185 lbs.,"74""",Orthodox,"Aug 06, 1992",3.26,56%,1.88,62%,1.37,80%,79%,0.3,Roman Dolidze,"6' 2""",205 lbs.,"76""",Orthodox,"Jul 15, 1988",2.98,51%,1.75,61%,1.75,50%,33%,2.2
2,Tai Tuivasa,Harry Hunsucker,Tai Tuivasa,Tai Tuivasa,"6' 2""",264 lbs.,"75""",Southpaw,"Mar 16, 1993",4.38,50%,3.44,50%,0.00,0%,46%,0.0,Harry Hunsucker,"6' 2""",241 lbs.,"75""",Orthodox,"Jan 03, 1989",4.33,51%,8.44,41%,0.00,0%,0%,0.0
3,Cheyanne Buys,Montserrat Conejo,Montserrat Conejo,Cheyanne Buys,"5' 3""",115 lbs.,"63""",Switch,"Jun 25, 1995",4.10,53%,1.67,65%,0.00,0%,60%,0.0,Montserrat Conejo,"5' 0""",115 lbs.,"61""",Southpaw,"Feb 03, 1993",1.00,36%,2.07,52%,4.00,80%,0%,2.0
4,Marion Reneau,Macy Chiasson,Macy Chiasson,Marion Reneau,"5' 6""",135 lbs.,"68""",Orthodox,"Jun 20, 1977",3.29,41%,3.37,61%,0.66,63%,50%,0.8,Macy Chiasson,"5' 11""",135 lbs.,"72""",Orthodox,"Jul 27, 1991",4.16,49%,2.17,46%,0.98,21%,64%,0.5

In [8]:
df.isna().sum()

R_fighter              0
B_fighter              0
Winner               110
fighter_name_Red       0
Height_Red             4
Weight_Red             2
Reach_Red            406
Stance_Red            29
DOB_Red               63
SLpM_Red               0
Str_Acc_Red            0
SApM_Red               0
Str_Def_Red            0
TD_Avg_Red             0
TD_Acc_Red             0
TD_Def_Red             0
Sub_Avg_Red            0
fighter_name_Blue      0
Height_Blue           10
Weight_Blue            8
Reach_Blue           891
Stance_Blue           66
DOB_Blue             172
SLpM_Blue              0
Str_Acc_Blue           0
SApM_Blue              0
Str_Def_Blue           0
TD_Avg_Blue            0
TD_Acc_Blue            0
TD_Def_Blue            0
Sub_Avg_Blue           0
dtype: int64

In [9]:
df = df.dropna(subset=['Winner','DOB_Red','DOB_Blue','Height_Red','Height_Blue','Weight_Blue','Weight_Red'])

In [10]:
df.isna().sum()

R_fighter              0
B_fighter              0
Winner                 0
fighter_name_Red       0
Height_Red             0
Weight_Red             0
Reach_Red            262
Stance_Red            22
DOB_Red                0
SLpM_Red               0
Str_Acc_Red            0
SApM_Red               0
Str_Def_Red            0
TD_Avg_Red             0
TD_Acc_Red             0
TD_Def_Red             0
Sub_Avg_Red            0
fighter_name_Blue      0
Height_Blue            0
Weight_Blue            0
Reach_Blue           693
Stance_Blue           37
DOB_Blue               0
SLpM_Blue              0
Str_Acc_Blue           0
SApM_Blue              0
Str_Def_Blue           0
TD_Avg_Blue            0
TD_Acc_Blue            0
TD_Def_Blue            0
Sub_Avg_Blue           0
dtype: int64

In [11]:
cols = ['Reach_Red','Reach_Blue','Stance_Red','Stance_Blue']
for i in cols:
    df[i] = df[i].fillna(df[i].mode()[0])

In [12]:
df.isna().sum()

R_fighter            0
B_fighter            0
Winner               0
fighter_name_Red     0
Height_Red           0
Weight_Red           0
Reach_Red            0
Stance_Red           0
DOB_Red              0
SLpM_Red             0
Str_Acc_Red          0
SApM_Red             0
Str_Def_Red          0
TD_Avg_Red           0
TD_Acc_Red           0
TD_Def_Red           0
Sub_Avg_Red          0
fighter_name_Blue    0
Height_Blue          0
Weight_Blue          0
Reach_Blue           0
Stance_Blue          0
DOB_Blue             0
SLpM_Blue            0
Str_Acc_Blue         0
SApM_Blue            0
Str_Def_Blue         0
TD_Avg_Blue          0
TD_Acc_Blue          0
TD_Def_Blue          0
Sub_Avg_Blue         0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5708 entries, 0 to 6005
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   R_fighter          5708 non-null   object
 1   B_fighter          5708 non-null   object
 2   Winner             5708 non-null   object
 3   fighter_name_Red   5708 non-null   object
 4   Height_Red         5708 non-null   object
 5   Weight_Red         5708 non-null   object
 6   Reach_Red          5708 non-null   object
 7   Stance_Red         5708 non-null   object
 8   DOB_Red            5708 non-null   object
 9   SLpM_Red           5708 non-null   float64
 10  Str_Acc_Red        5708 non-null   object
 11  SApM_Red           5708 non-null   float64
 12  Str_Def_Red        5708 non-null   object
 13  TD_Avg_Red         5708 non-null   float64
 14  TD_Acc_Red         5708 non-null   object
 15  TD_Def_Red         5708 non-null   object
 16  Sub_Avg_Red        5708 non-null   float64
 17  fighter_name_Blue  5708 non-null   object
 18  Height_Blue        5708 non-null   object
 19  Weight_Blue        5708 non-null   object
 20  Reach_Blue         5708 non-null   object
 21  Stance_Blue        5708 non-null   object
 22  DOB_Blue           5708 non-null   object
 23  SLpM_Blue          5708 non-null   float64
 24  Str_Acc_Blue       5708 non-null   object
 25  SApM_Blue          5708 non-null   float64
 26  Str_Def_Blue       5708 non-null   object
 27  TD_Avg_Blue        5708 non-null   float64
 28  TD_Acc_Blue        5708 non-null   object
 29  TD_Def_Blue        5708 non-null   object
 30  Sub_Avg_Blue       5708 non-null   float64
dtypes: float64(8), object(23)
memory usage: 1.4+ MB

In [14]:
df.head()

,R_fighter,B_fighter,Winner,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,DOB_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,fighter_name_Blue,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,DOB_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue
0,Adrian Yanez,Gustavo Lopez,Adrian Yanez,Adrian Yanez,"5' 7""",135 lbs.,"70""",Orthodox,"Nov 29, 1993",4.69,44%,2.31,55%,0.00,0%,100%,0.0,Gustavo Lopez,"5' 5""",135 lbs.,"67""",Orthodox,"Jun 27, 1989",2.24,41%,4.65,51%,1.07,50%,27%,0.5
1,Trevin Giles,Roman Dolidze,Trevin Giles,Trevin Giles,"6' 0""",185 lbs.,"74""",Orthodox,"Aug 06, 1992",3.26,56%,1.88,62%,1.37,80%,79%,0.3,Roman Dolidze,"6' 2""",205 lbs.,"76""",Orthodox,"Jul 15, 1988",2.98,51%,1.75,61%,1.75,50%,33%,2.2
2,Tai Tuivasa,Harry Hunsucker,Tai Tuivasa,Tai Tuivasa,"6' 2""",264 lbs.,"75""",Southpaw,"Mar 16, 1993",4.38,50%,3.44,50%,0.00,0%,46%,0.0,Harry Hunsucker,"6' 2""",241 lbs.,"75""",Orthodox,"Jan 03, 1989",4.33,51%,8.44,41%,0.00,0%,0%,0.0
3,Cheyanne Buys,Montserrat Conejo,Montserrat Conejo,Cheyanne Buys,"5' 3""",115 lbs.,"63""",Switch,"Jun 25, 1995",4.10,53%,1.67,65%,0.00,0%,60%,0.0,Montserrat Conejo,"5' 0""",115 lbs.,"61""",Southpaw,"Feb 03, 1993",1.00,36%,2.07,52%,4.00,80%,0%,2.0
4,Marion Reneau,Macy Chiasson,Macy Chiasson,Marion Reneau,"5' 6""",135 lbs.,"68""",Orthodox,"Jun 20, 1977",3.29,41%,3.37,61%,0.66,63%,50%,0.8,Macy Chiasson,"5' 11""",135 lbs.,"72""",Orthodox,"Jul 27, 1991",4.16,49%,2.17,46%,0.98,21%,64%,0.5

In [15]:
df['Height_Red'] = df['Height_Red'].str.replace("'",".")
df['Height_Red'] = df['Height_Red'].str.replace('"','')
df['Height_Red'] = df['Height_Red'].str.replace(" ","")
df['Height_Red'] = df['Height_Red'].astype(float)

In [16]:
df['Weight_Red'] = df['Weight_Red'].str.replace(' lbs.','').astype(int)

C:\Users\Katta\AppData\Local\Temp\ipykernel_6672\3967962349.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Weight_Red'] = df['Weight_Red'].str.replace(' lbs.','').astype(int)

In [17]:
df['Reach_Red'] = df['Reach_Red'].str.replace('"','').astype(int)
df['Height_Blue'] = df['Height_Blue'].str.replace("'",".")
df['Height_Blue'] = df['Height_Blue'].str.replace('"','')
df['Height_Blue'] = df['Height_Blue'].str.replace(" ","")
df['Height_Blue'] = df['Height_Blue'].astype(float)
df['Reach_Blue'] = df['Reach_Blue'].str.replace('"','').astype(int)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5708 entries, 0 to 6005
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   R_fighter          5708 non-null   object
 1   B_fighter          5708 non-null   object
 2   Winner             5708 non-null   object
 3   fighter_name_Red   5708 non-null   object
 4   Height_Red         5708 non-null   float64
 5   Weight_Red         5708 non-null   int32
 6   Reach_Red          5708 non-null   int32
 7   Stance_Red         5708 non-null   object
 8   DOB_Red            5708 non-null   object
 9   SLpM_Red           5708 non-null   float64
 10  Str_Acc_Red        5708 non-null   object
 11  SApM_Red           5708 non-null   float64
 12  Str_Def_Red        5708 non-null   object
 13  TD_Avg_Red         5708 non-null   float64
 14  TD_Acc_Red         5708 non-null   object
 15  TD_Def_Red         5708 non-null   object
 16  Sub_Avg_Red        5708 non-null   float64
 17  fighter_name_Blue  5708 non-null   object
 18  Height_Blue        5708 non-null   float64
 19  Weight_Blue        5708 non-null   object
 20  Reach_Blue         5708 non-null   int32
 21  Stance_Blue        5708 non-null   object
 22  DOB_Blue           5708 non-null   object
 23  SLpM_Blue          5708 non-null   float64
 24  Str_Acc_Blue       5708 non-null   object
 25  SApM_Blue          5708 non-null   float64
 26  Str_Def_Blue       5708 non-null   object
 27  TD_Avg_Blue        5708 non-null   float64
 28  TD_Acc_Blue        5708 non-null   object
 29  TD_Def_Blue        5708 non-null   object
 30  Sub_Avg_Blue       5708 non-null   float64
dtypes: float64(10), int32(3), object(18)
memory usage: 1.3+ MB

In [19]:
df.head()

,R_fighter,B_fighter,Winner,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,DOB_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,fighter_name_Blue,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,DOB_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue
0,Adrian Yanez,Gustavo Lopez,Adrian Yanez,Adrian Yanez,5.7,135,70,Orthodox,"Nov 29, 1993",4.69,44%,2.31,55%,0.00,0%,100%,0.0,Gustavo Lopez,5.50,135 lbs.,67,Orthodox,"Jun 27, 1989",2.24,41%,4.65,51%,1.07,50%,27%,0.5
1,Trevin Giles,Roman Dolidze,Trevin Giles,Trevin Giles,6.0,185,74,Orthodox,"Aug 06, 1992",3.26,56%,1.88,62%,1.37,80%,79%,0.3,Roman Dolidze,6.20,205 lbs.,76,Orthodox,"Jul 15, 1988",2.98,51%,1.75,61%,1.75,50%,33%,2.2
2,Tai Tuivasa,Harry Hunsucker,Tai Tuivasa,Tai Tuivasa,6.2,264,75,Southpaw,"Mar 16, 1993",4.38,50%,3.44,50%,0.00,0%,46%,0.0,Harry Hunsucker,6.20,241 lbs.,75,Orthodox,"Jan 03, 1989",4.33,51%,8.44,41%,0.00,0%,0%,0.0
3,Cheyanne Buys,Montserrat Conejo,Montserrat Conejo,Cheyanne Buys,5.3,115,63,Switch,"Jun 25, 1995",4.10,53%,1.67,65%,0.00,0%,60%,0.0,Montserrat Conejo,5.00,115 lbs.,61,Southpaw,"Feb 03, 1993",1.00,36%,2.07,52%,4.00,80%,0%,2.0
4,Marion Reneau,Macy Chiasson,Macy Chiasson,Marion Reneau,5.6,135,68,Orthodox,"Jun 20, 1977",3.29,41%,3.37,61%,0.66,63%,50%,0.8,Macy Chiasson,5.11,135 lbs.,72,Orthodox,"Jul 27, 1991",4.16,49%,2.17,46%,0.98,21%,64%,0.5

In [20]:
df['Str_Acc_Red'] = df['Str_Acc_Red'].str.replace('%','').astype(int)
df['TD_Acc_Red'] = df['TD_Acc_Red'].str.replace('%','').astype(int)
df['TD_Def_Red'] = df['TD_Def_Red'].str.replace('%','').astype(int)
df['Weight_Blue'] = df['Weight_Blue'].str.replace(' lbs.','').astype(int)
df['Str_Acc_Blue'] = df['Str_Acc_Blue'].str.replace('%','').astype(int)
df['TD_Acc_Blue'] = df['TD_Acc_Blue'].str.replace('%','').astype(int)
df['TD_Def_Blue'] = df['TD_Def_Blue'].str.replace('%','').astype(int)

C:\Users\Katta\AppData\Local\Temp\ipykernel_6672\2350955266.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Weight_Blue'] = df['Weight_Blue'].str.replace(' lbs.','').astype(int)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5708 entries, 0 to 6005
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   R_fighter          5708 non-null   object
 1   B_fighter          5708 non-null   object
 2   Winner             5708 non-null   object
 3   fighter_name_Red   5708 non-null   object
 4   Height_Red         5708 non-null   float64
 5   Weight_Red         5708 non-null   int32
 6   Reach_Red          5708 non-null   int32
 7   Stance_Red         5708 non-null   object
 8   DOB_Red            5708 non-null   object
 9   SLpM_Red           5708 non-null   float64
 10  Str_Acc_Red        5708 non-null   int32
 11  SApM_Red           5708 non-null   float64
 12  Str_Def_Red        5708 non-null   object
 13  TD_Avg_Red         5708 non-null   float64
 14  TD_Acc_Red         5708 non-null   int32
 15  TD_Def_Red         5708 non-null   int32
 16  Sub_Avg_Red        5708 non-null   float64
 17  fighter_name_Blue  5708 non-null   object
 18  Height_Blue        5708 non-null   float64
 19  Weight_Blue        5708 non-null   int32
 20  Reach_Blue         5708 non-null   int32
 21  Stance_Blue        5708 non-null   object
 22  DOB_Blue           5708 non-null   object
 23  SLpM_Blue          5708 non-null   float64
 24  Str_Acc_Blue       5708 non-null   int32
 25  SApM_Blue          5708 non-null   float64
 26  Str_Def_Blue       5708 non-null   object
 27  TD_Avg_Blue        5708 non-null   float64
 28  TD_Acc_Blue        5708 non-null   int32
 29  TD_Def_Blue        5708 non-null   int32
 30  Sub_Avg_Blue       5708 non-null   float64
dtypes: float64(10), int32(10), object(11)
memory usage: 1.2+ MB

In [22]:
df['Str_Def_Red'] =  df['Str_Def_Red'].str.replace('%','').astype(int)

In [23]:
df['Str_Def_Blue'] =  df['Str_Def_Blue'].str.replace('%','').astype(int)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5708 entries, 0 to 6005
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   R_fighter          5708 non-null   object
 1   B_fighter          5708 non-null   object
 2   Winner             5708 non-null   object
 3   fighter_name_Red   5708 non-null   object
 4   Height_Red         5708 non-null   float64
 5   Weight_Red         5708 non-null   int32
 6   Reach_Red          5708 non-null   int32
 7   Stance_Red         5708 non-null   object
 8   DOB_Red            5708 non-null   object
 9   SLpM_Red           5708 non-null   float64
 10  Str_Acc_Red        5708 non-null   int32
 11  SApM_Red           5708 non-null   float64
 12  Str_Def_Red        5708 non-null   int32
 13  TD_Avg_Red         5708 non-null   float64
 14  TD_Acc_Red         5708 non-null   int32
 15  TD_Def_Red         5708 non-null   int32
 16  Sub_Avg_Red        5708 non-null   float64
 17  fighter_name_Blue  5708 non-null   object
 18  Height_Blue        5708 non-null   float64
 19  Weight_Blue        5708 non-null   int32
 20  Reach_Blue         5708 non-null   int32
 21  Stance_Blue        5708 non-null   object
 22  DOB_Blue           5708 non-null   object
 23  SLpM_Blue          5708 non-null   float64
 24  Str_Acc_Blue       5708 non-null   int32
 25  SApM_Blue          5708 non-null   float64
 26  Str_Def_Blue       5708 non-null   int32
 27  TD_Avg_Blue        5708 non-null   float64
 28  TD_Acc_Blue        5708 non-null   int32
 29  TD_Def_Blue        5708 non-null   int32
 30  Sub_Avg_Blue       5708 non-null   float64
dtypes: float64(10), int32(12), object(9)
memory usage: 1.1+ MB

In [25]:
df = df.drop(columns=['R_fighter','B_fighter','DOB_Red','DOB_Blue'])

In [26]:
df.head()

,Winner,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,fighter_name_Blue,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue
0,Adrian Yanez,Adrian Yanez,5.7,135,70,Orthodox,4.69,44,2.31,55,0.00,0,100,0.0,Gustavo Lopez,5.50,135,67,Orthodox,2.24,41,4.65,51,1.07,50,27,0.5
1,Trevin Giles,Trevin Giles,6.0,185,74,Orthodox,3.26,56,1.88,62,1.37,80,79,0.3,Roman Dolidze,6.20,205,76,Orthodox,2.98,51,1.75,61,1.75,50,33,2.2
2,Tai Tuivasa,Tai Tuivasa,6.2,264,75,Southpaw,4.38,50,3.44,50,0.00,0,46,0.0,Harry Hunsucker,6.20,241,75,Orthodox,4.33,51,8.44,41,0.00,0,0,0.0
3,Montserrat Conejo,Cheyanne Buys,5.3,115,63,Switch,4.10,53,1.67,65,0.00,0,60,0.0,Montserrat Conejo,5.00,115,61,Southpaw,1.00,36,2.07,52,4.00,80,0,2.0
4,Macy Chiasson,Marion Reneau,5.6,135,68,Orthodox,3.29,41,3.37,61,0.66,63,50,0.8,Macy Chiasson,5.11,135,72,Orthodox,4.16,49,2.17,46,0.98,21,64,0.5

In [27]:
def winner(x,red,blue):
    if red in x:
        return 1
    elif blue in x:
        return 0

In [28]:
df['winner_color'] = df[['Winner','fighter_name_Red','fighter_name_Blue']].apply(lambda x: winner(x['Winner'], x['fighter_name_Red'], x['fighter_name_Blue']), axis=1)

In [29]:
df.head()

,Winner,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,fighter_name_Blue,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue,winner_color
0,Adrian Yanez,Adrian Yanez,5.7,135,70,Orthodox,4.69,44,2.31,55,0.00,0,100,0.0,Gustavo Lopez,5.50,135,67,Orthodox,2.24,41,4.65,51,1.07,50,27,0.5,1
1,Trevin Giles,Trevin Giles,6.0,185,74,Orthodox,3.26,56,1.88,62,1.37,80,79,0.3,Roman Dolidze,6.20,205,76,Orthodox,2.98,51,1.75,61,1.75,50,33,2.2,1
2,Tai Tuivasa,Tai Tuivasa,6.2,264,75,Southpaw,4.38,50,3.44,50,0.00,0,46,0.0,Harry Hunsucker,6.20,241,75,Orthodox,4.33,51,8.44,41,0.00,0,0,0.0,1
3,Montserrat Conejo,Cheyanne Buys,5.3,115,63,Switch,4.10,53,1.67,65,0.00,0,60,0.0,Montserrat Conejo,5.00,115,61,Southpaw,1.00,36,2.07,52,4.00,80,0,2.0,0
4,Macy Chiasson,Marion Reneau,5.6,135,68,Orthodox,3.29,41,3.37,61,0.66,63,50,0.8,Macy Chiasson,5.11,135,72,Orthodox,4.16,49,2.17,46,0.98,21,64,0.5,0

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Stance_Red'] = le.fit_transform(df['Stance_Red'])
df['Stance_Blue'] = le.fit_transform(df['Stance_Blue'])

In [33]:
df_red = df.iloc[:,1:14]
df_blue = df.iloc[:,14:-1]

df_red.to_csv('df_red.csv')
df_blue.to_csv('df_blue.csv')

In [34]:
df = df.drop(['fighter_name_Blue','fighter_name_Red','Winner'],axis=1)

In [35]:
df.head()

,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue,winner_color
0,5.7,135,70,1,4.69,44,2.31,55,0.00,0,100,0.0,5.50,135,67,1,2.24,41,4.65,51,1.07,50,27,0.5,1
1,6.0,185,74,1,3.26,56,1.88,62,1.37,80,79,0.3,6.20,205,76,1,2.98,51,1.75,61,1.75,50,33,2.2,1
2,6.2,264,75,2,4.38,50,3.44,50,0.00,0,46,0.0,6.20,241,75,1,4.33,51,8.44,41,0.00,0,0,0.0,1
3,5.3,115,63,3,4.10,53,1.67,65,0.00,0,60,0.0,5.00,115,61,3,1.00,36,2.07,52,4.00,80,0,2.0,0
4,5.6,135,68,1,3.29,41,3.37,61,0.66,63,50,0.8,5.11,135,72,1,4.16,49,2.17,46,0.98,21,64,0.5,0

In [36]:
df.head()

,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red,Height_Blue,Weight_Blue,Reach_Blue,Stance_Blue,SLpM_Blue,Str_Acc_Blue,SApM_Blue,Str_Def_Blue,TD_Avg_Blue,TD_Acc_Blue,TD_Def_Blue,Sub_Avg_Blue,winner_color
0,5.7,135,70,1,4.69,44,2.31,55,0.00,0,100,0.0,5.50,135,67,1,2.24,41,4.65,51,1.07,50,27,0.5,1
1,6.0,185,74,1,3.26,56,1.88,62,1.37,80,79,0.3,6.20,205,76,1,2.98,51,1.75,61,1.75,50,33,2.2,1
2,6.2,264,75,2,4.38,50,3.44,50,0.00,0,46,0.0,6.20,241,75,1,4.33,51,8.44,41,0.00,0,0,0.0,1
3,5.3,115,63,3,4.10,53,1.67,65,0.00,0,60,0.0,5.00,115,61,3,1.00,36,2.07,52,4.00,80,0,2.0,0
4,5.6,135,68,1,3.29,41,3.37,61,0.66,63,50,0.8,5.11,135,72,1,4.16,49,2.17,46,0.98,21,64,0.5,0

In [37]:
X = df.drop(['winner_color'],axis=1)
y = df['winner_color']

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42, max_depth=100)
rf = RandomForestClassifier(random_state=42)
lr = LogisticRegression(random_state=42, max_iter=15000)

#rf.fit(X_train,y_train)
lr.fit(X_train,y_train)
#dt.fit(X_train,y_train)

LogisticRegression(max_iter=15000, random_state=42)

In [45]:
lr.score(X_test,y_test)

0.7005253940455342

In [46]:
import pickle

In [47]:
with open('log_reg','wb') as f:
    pickle.dump(lr,f)

In [51]:
df_red['fighter_name_Red'].values

array(['Adrian Yanez', 'Trevin Giles', 'Tai Tuivasa', ..., 'Royce Gracie',
       'Royce Gracie', 'Royce Gracie'], dtype=object)

In [54]:
df_red[df_red['fighter_name_Red']=='Adrian Yanez']

,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red
0,Adrian Yanez,5.7,135,70,Orthodox,4.69,44,2.31,55,0.0,0,100,0.0
188,Adrian Yanez,5.7,135,70,Orthodox,4.69,44,2.31,55,0.0,0,100,0.0

In [55]:
df_red[df_red['fighter_name_Red']=='Belal Muhammad']

,fighter_name_Red,Height_Red,Weight_Red,Reach_Red,Stance_Red,SLpM_Red,Str_Acc_Red,SApM_Red,Str_Def_Red,TD_Avg_Red,TD_Acc_Red,TD_Def_Red,Sub_Avg_Red
60,Belal Muhammad,5.11,170,72,Orthodox,4.75,43,4.02,60,1.97,28,85,0.2
403,Belal Muhammad,5.11,170,72,Orthodox,4.75,43,4.02,60,1.97,28,85,0.2
743,Belal Muhammad,5.11,170,72,Orthodox,4.75,43,4.02,60,1.97,28,85,0.2
1087,Belal Muhammad,5.11,170,72,Orthodox,4.75,43,4.02,60,1.97,28,85,0.2
1386,Belal Muhammad,5.11,170,72,Orthodox,4.75,43,4.02,60,1.97,28,85,0.2

In [60]:
list(set(df_blue['fighter_name_Blue'])).index('Khamzat Chimaev')

544